CREATE DATABASE test;
USE test;
CREATE TABLE roles (id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
					createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    label VARCHAR(50) NOT NULL);